SELECT NAME,COUNTRY,NUMGUNS,LAUNCHED
FROM SHIPS
JOIN CLASSES c on c.CLASS=SHIPS.CLASS

UNION ALL

SELECT NAME,COUNTRY,NUMGUNS,LAUNCHED
FROM CLASSES
LEFT JOIN SHIPS S on s.CLASS=CLASSES.CLASS
WHERE CLASSES.class not in (SELECT DISTINCT CLASS from ships) AND
CLASSES.class in (SELECT NAME FROM SHIPS)