-- SELECT m1.TITLE
-- FROM MOVIE m1, MOVIE m2
-- WHERE m2.TITLE='Gone With the Wind'
-- AND m1.LENGTH > m2.LENGTH

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH 
				FROM MOVIE 
				WHERE TITLE='Gone With the Wind')