-- SELECT NAME
-- FROM STARSIN JOIN MOVIESTAR ON STARNAME=NAME
-- WHERE MOVIETITLE='Terms of Endearment' AND GENDER='M'


SELECT NAME
FROM MOVIESTAR JOIN STARSIN ON STARNAME=NAME
WHERE MOVIETITLE='Terms of Endearment' AND GENDER='M'

-- SELECT NAME
-- FROM STARSIN s, MOVIESTAR m
-- WHERE s.STARNAME=m.NAME AND s.MOVIETITLE ='Terms of Endearment' AND m.GENDER='M'