ALTER TABLE STUDIO
ADD PRESIDENT_NAME VARCHAR(255);

UPDATE STUDIO
SET PRESIDENT_NAME = 'Robert Iger'
WHERE NAME='Disney';

UPDATE STUDIO
SET PRESIDENT_NAME = 'Gary Newman '
WHERE NAME='Fox';

UPDATE STUDIO
SET PRESIDENT_NAME = 'Louis B. Mayerr'
WHERE NAME='MGM';

UPDATE STUDIO
SET PRESIDENT_NAME = 'Jim Gianopulos'
WHERE NAME='Paramount';

UPDATE STUDIO
SET PRESIDENT_NAME =  'Jonathan King'
WHERE NAME='USA Entertainm.';


UPDATE STUDIO
SET PRESIDENT_NAME = 'Kevin Tsujihara'
WHERE NAME='Warner Bros';

SELECT PRESIDENT_NAME
FROM STUDIO
WHERE NAME='MGM';
